#TEMPLATE TO RUN PROGRAM f003

EXECBASE=f003
EXECUTABLE=$PWD/$EXECBASE.exe
OUTPUT_DIR=$PWD/OUTPUT/
#INPUT_DIR=$PWD/INPUT/

#INPUT FILES
#INPUT=${INPUT_DIR}

echo 'No input required for f003'

#OUTPUT

echo 'Output going to ' ${OUTPUT_DIR}f003.out

$EXECUTABLE > ${OUTPUT_DIR}f003.out

echo ' '
echo 'PROGRAM f003 HAS ENDED'
#END KSH
